# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task: graphql

  graphql:
    desc: "Generate GraphQL code"
    cmds:
      - go tool gqlgen generate

  mock:
    aliases:
      - m
    desc: "Generate mock files"
    cmds:
      - echo "Mock generation will be added when interfaces are defined"

  build:frontend:
    desc: "Build frontend application"
    dir: frontend
    cmds:
      - pnpm install --frozen-lockfile
      - pnpm run build
      - touch dist/.gitkeep

  dev:frontend:
    desc: "Run frontend development server"
    dir: frontend
    cmds:
      - pnpm run dev
